version: '3.8'

services:
  wordpress:
    restart: always
    image: wordpress:6.0.2
    ports:
      - 8080:80
    volumes:
      - db-wordpress:/var/www/html

  mysql:
    image: mysql:8.0.31
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: usr123
      MYSQL_ROOT_PASSWORD: usr123
    volumes:
      - db-mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 4040:8080

volumes:
  db-wordpress:
  db-mysql:
  